name: 'Executing Nonsible'
description: 'Custom action that executes Nonsible'

inputs:
  targetYAML:
    description: 'The YAML file that contains the connections data.'
    required: true
  taskYAML:
    description: 'The YAML file that contains the tasks to run.'
    required: true
  force:
    description: 'Runs Nonsible even if a connection is failed.'
    required: false
  continueonerror:
    description: "Runs Nonsible even if a connection failed, and executes every task on failed connections too."
    required: false
  nocolor:
    description: 'Print more information about the tasks, but could print some sensible data.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Log check
      shell: bash
      run: echo "Executing the Nonsible custom action"

    - name: Setting up arguments
      id: setup_args
      shell: bash
      run: |
        args=""

        if [ "${{ inputs.force }}" != false ]; then
          args+=" --force"
        fi
        if [ "${{ inputs.continueonerror }}" != false ]; then
          args+=" --continueonerror"
        fi
        if [ "${{ inputs.nocolor }}" != false ]; then
          args+=" --no-color"
        fi

        echo "setup_args=$args" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT

    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "NeddM/nonsible"
        latest: true
        fileName: "nonsible"
    
    - name: chmod
      shell: bash
      run: chmod 777 nonsible

    - name: Run the aplication
      shell: bash
      run: ./nonsible ${{ inputs.targetYAML }} ${{ inputs.taskYAML }} ${{ steps.setup_args.outputs.setup_args }}
