run-name: Example executing Nonsible
name: Example executing Nonsible

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar entorno
      uses: NeddM/nonsible@v0.1
      with:
        # Required arguments
        targetYAML: ./examples/testing-labels.yaml
        taskYAML: ./examples/apache-tasks.yaml
        # The arguments bellow are optional
        continueonerror: false
        force: false
        nocolor: true
