run-name: Example executing Nonsible
name: Example executing Nonsible

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Chmod the keys
      run: |
        chmod 400 ./pem/piensa
        chmod 400 ./pem/raspi

    - name: Nonsible
      uses: NeddM/nonsible@v0.1
      with:
        # Required arguments
        targetYAML: ./examples/testing-labels.yaml
        taskYAML: ./examples/apache-tasks.yaml
        # Optional arguments
        continueonerror: false
        force: false
        nocolor: true
